apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}--dss-pws
  namespace: theatre-east
  labels: 
    name: passwordsafe-integration
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: passwordsafe-integration
  template:
    metadata:
      labels:
        name:  passwordsafe-integration
    spec:
      volumes:
      - name: secretss
        configMap:
          name: full-coral-configmap
          defaultMode: 0777
      - name: secrets
        emptyDir: {}
      initContainers:
        - name: secrets-agent
          image: beyondtrust/secrets-agent:latest
          volumeMounts:
            - name: secrets
              mountPath: /usr/src/app/k8s
          ports:
            - containerPort: 8080
          env:
          - name: SECRETS_PATH
            value: "/usr/src/app/k8s"
          - name: BT_API_URL            
            valueFrom:
              secretKeyRef:
                name: newsecret
                key: BT_API_URL
          - name: BT_API_KEY
            valueFrom:
              secretKeyRef:
                name: newsecret
                key: BT_API_KEY
          - name: SECRETS_LIST
            value: "k8s/k8s.txt"
          - name: MANAGED_ACCOUNTS_LIST
            value: "masterk8s/paul"
          - name: BT_VERIFY_CA
            value: "False"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
          - /root/test.sh
          - sleep 86400
          volumeMounts:
            - name: secrets
              mountPath: /usr/src/app/k8s
            - name: secretss
              mountPath: "/root/test.sh"
              subPath: test.sh
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: {{ .Values.service.protocol | default "TCP" }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
